version: '3.8'

services:
  database:
    container_name: toktik_db_user_service
    image: postgres:16
    environment:
      POSTGRES_DB: toktik_user
      POSTGRES_USER: toktik_user
      POSTGRES_PASSWORD: toktik_user
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
