### Signup
POST http://localhost:8250/api/v1/auth/signup
Content-Type: application/json

{
  "username": "test",
  "firstname": "test",
  "lastname" : "user",
  "gender" : "MALE",
  "email": "testuser@example.com",
  "password": "test",
  "birthday": "1995-06-15"
}

### Login
POST http://localhost:8123/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser",
  "password": "securepassword"
}

### Get Profile with UUID
GET http://localhost:8250/api/v1/auth/me/2cd94e9d-437d-4592-ae87-8852b66bd49c
Accept: application/json
