### Signup
POST http://localhost:8123/api/v1/auth/signup
Content-Type: application/json

{
  "username": "testuser",
  "firstname": "test",
  "lastname" : "user",
  "gender" : "FEMALE",
  "email": "testuser@example.com",
  "password": "test",
  "birthday": "1995-06-15"
}

### Login
POST http://localhost:8123/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser",
  "password": "securepassword"
}

### Get Profile (Replace {{token}} with actual token from login response)
GET http://localhost:8080/api/v1/auth/me
Authorization: Bearer {{token}}
