spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/toktik_user
    username: toktik_user
    password: toktik_user
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8123