spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/toktik_user
    username: toktik_user
    password: toktik_user
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.52.84.18:8761/eureka

server:
  port: 8123